version: '3.7'
networks:
    LEMP-NW-DOMAIN_NAME:



#SFTPgo

  sftpgo:
    image: "drakkan/sftpgo:v2-alpine"
    # default user id
    user: "1026"
    restart: always
    expose:
      # HTTP
      - "8080"
      # HTTPS
      - "443"
      # WebDav
      - "5007"
    environment:
      # These are the settings to access your db
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 5007
      SFTPGO_DATA_PROVIDER__DRIVER: "mysql"
      SFTPGO_DATA_PROVIDER__NAME: "sftpgo"
      SFTPGO_DATA_PROVIDER__HOST: "mariaDB"
      SFTPGO_DATA_PROVIDER__PORT: 3306
      SFTPGO_DATA_PROVIDER__USERNAME: "sftp-user"
      SFTPGO_DATA_PROVIDER__PASSWORD: "my_cool_secret"
      SFTPGO_COMMON_DEFENDER__ENABLED: "true"
      SFTPGO_COMMON_DEFENDER__BAN_TIME: 15
      SFTPGO_COMMON_DEFENDER__BAN_TIME_INCREMENT: 100
      SFTPGO_COMMON_DEFENDER__THRESHOLD: 5
      SFTPGO_COMMON_DEFENDER__OBSERVATION_TIME: 15
    volumes:
      - ./:/srv/sftpgo
    networks:
      - LEMP-NW-DOMAIN_NAME

#PHP Service
  app:
    image: docker.io/bitnami/php-fpm:7.4-debian-10
    container_name: DOMAIN_NAME-app 
    restart: always
    tty: true
    ports:
      - 9000:9000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www/:/var/www
      - ./data/php/local.ini:/opt/bitnami/php/etc/conf.d/local.ini #if you need any custom php.ini customizations
      - ./logs:/var/log/
    networks:
      - LEMP-NW-DOMAIN_NAME

  mariaDB:
      image: mariadb:10.2
      container_name: DOMAIN_NAME-mariaDB
      volumes:
            - ./data/mysql/database:/var/lib/mysql:rw
            - ./data/mysql/mysql/my.cnf:/etc/mysql/my.cnf
      ports:
            - "3306:3306"
      depends_on:
            - nginx
      env_file:
      - ./data/mysql/mariadb.env
      environment:
            - MYSQL_ROOT_PASSWORD=654321
            - MARIADB_USER=sftp-user
            - MARIADB_PASSWORD=my_cool_secret
            - MARIADB_DATABASE: "sftpgo" 
      networks:
            - LEMP-NW-DOMAIN_NAME

#phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: DOMAIN_NAME-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mariaDB
      - nginx
    networks:
      - LEMP-NW-DOMAIN_NAME

